"""add origin field

Revision ID: 22e90c16a32d
Revises: 81e6e974aa9c
Create Date: 2025-02-12 22:04:27.759203

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22e90c16a32d"
down_revision: Union[str, None] = "81e6e974aa9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reit", sa.Column("origin", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column(
        "stock", sa.Column("origin", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock", "origin")
    op.drop_column("reit", "origin")
    # ### end Alembic commands ###
