"""add ticker table

Revision ID: 3e87d6688d30
Revises: 22e90c16a32d
Create Date: 2025-02-16 13:18:59.800279

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

import app

# revision identifiers, used by Alembic.
revision: str = "3e87d6688d30"
down_revision: Union[str, None] = "22e90c16a32d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticker",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("help", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "type", sa.Enum("STOCK", "REIT", name="tickertypeenum"), nullable=False
        ),
        sa.Column(
            "created_at", app.common.model.type.DateTimeWithTimeZone(), nullable=False
        ),
        sa.Column(
            "updated_at", app.common.model.type.DateTimeWithTimeZone(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ticker_symbol"), "ticker", ["symbol"], unique=True)
    op.create_index(op.f("ix_ticker_type"), "ticker", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticker_type"), table_name="ticker")
    op.drop_index(op.f("ix_ticker_symbol"), table_name="ticker")
    op.drop_table("ticker")
    # ### end Alembic commands ###
