"""add reit document field

Revision ID: cb58710e0c13
Revises: 3e87d6688d30
Create Date: 2025-05-24 21:50:05.401302

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb58710e0c13"
down_revision: Union[str, None] = "3e87d6688d30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reit",
        sa.Column("document", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reit", "document")
    # ### end Alembic commands ###
